CREATE TABLE IF NOT EXISTS public.student_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500),
    file_type VARCHAR(50),
    file_size BIGINT,
    status VARCHAR(20) DEFAULT 'Pending',
    rejection_reason TEXT,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    reviewed_by VARCHAR(100),
    CONSTRAINT fk_student_documents_student FOREIGN KEY (student_id) REFERENCES public.students (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_student_documents_student_id ON public.student_documents(student_id);
