START TRANSACTION;
ALTER TABLE public.courses ADD period_id integer;

CREATE TABLE public.school_periods (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(50) NOT NULL,
    start_date timestamp with time zone NOT NULL,
    end_date timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_school_periods" PRIMARY KEY (id)
);

CREATE INDEX "IX_courses_period_id" ON public.courses (period_id);

ALTER TABLE public.courses ADD CONSTRAINT "FK_courses_school_periods_period_id" FOREIGN KEY (period_id) REFERENCES public.school_periods (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260217211438_AddSchoolPeriodTable', '9.0.0');

COMMIT;

