-- Create question_pools table
CREATE TABLE IF NOT EXISTS public.question_pools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create pool_questions table
CREATE TABLE IF NOT EXISTS public.pool_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pool_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    question_type VARCHAR(50) NOT NULL, -- 'multiple_choice', 'true_false', 'open'
    options_json JSONB, -- For multiple choice options
    correct_answer_json JSONB, -- To store the correct answer(s)
    points DECIMAL(5,2) DEFAULT 1.0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT fk_pool FOREIGN KEY (pool_id) REFERENCES public.question_pools (id) ON DELETE CASCADE
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_question_pools_teacher_id ON public.question_pools(teacher_id);
CREATE INDEX IF NOT EXISTS idx_pool_questions_pool_id ON public.pool_questions(pool_id);
