-- Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id bigint NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    type character varying(50) DEFAULT 'General',
    reference_id bigint NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT "PK_notifications" PRIMARY KEY (id),
    CONSTRAINT "FK_notifications_students_student_id" FOREIGN KEY (student_id) REFERENCES public.students (id) ON DELETE CASCADE
);

CREATE INDEX "IX_notifications_student_id" ON public.notifications (student_id);
